### ISSUE TITLE
nCount_peaks vs peak_region_fragments

### ISSUE THREAD

**Issue by fmarzetta** [stuart-lab/signac#1282]
Hello,

I have Single Cell Multiome data that I am processing using Signac and Seurat.
Could you please comment on the difference between the 2 metrics describing the number of reads in peaks ("nCount_peaks" and "peak_region_fragments")?
As explained in a previous post (https://github.com/stuart-lab/signac/issues/19), the first comes from Seurat while the second from Cell Ranger and they highly correlate.
However, "peak_region_fragments" contains about half the peaks quantified in "nCount_peaks".

How was the read counting performed? Was there a difference in the evaluation of the overlap between reads and peaks?
Also, are there analyses where the "peak_region_fragments" metrics should be preferred?

Many thanks in advance for your answer.

Best regards

**Comment by timoast** [comment]
This is due to the difference between counting insertion sites and counting fragments. Tn5 insertion site counts (reported by cellranger) is approximately half the fragment count. nCount_peaks is the number of total counts for the cell from the assay in a Seurat object named “peaks,” it is the column sum of the count matrix
