### ISSUE TITLE
Input genome for CreateChromatinAssay

### ISSUE THREAD

**Issue by Liang6292** [stuart-lab/signac#1291]
Hi there,
I got some trouble creating a chromatinassay object using Singac package. It seems to only support the NCBI or UCSC assemblies/genomes currently registered in the GenomeInfoDb package. Then I tried a registered UCSC genome (gasAcu1), but the package reported an error as ‘Annotation genome does not match genome of the object’. So I wonder if it is possible to use my own .fna file as an input of the genome when creating the chromatinassay object. Any suggestions? Thanks in advance.

**Comment by timoast** [comment]
The error "Annotation genome does not match genome of the object" is because we perform a check that the genome name you provide when creating the object matches the genome information for the gene annotations you're adding. This is just to try to avoid mistakes. If you're sure that the genome information is correct, you can just not set the `genome` parameter when creating the Seurat object and this check will be skipped
