### ISSUE TITLE
IntegrateData() scATAC Integration Error

### ISSUE THREAD

**Issue by aliamrod** [stuart-lab/signac#1372]
For weeks, I have been trying to run IntegrateData() into my scATAC-seq integration. Currently the motive is to merge datasets and consequently integrate the different biological conditions together in order to generate one, singular integrated dataset for downstream processing. 

Code snippet is attached below:
```
object.list = list(sample1,sample2, sample3, sample4, sample5)

integration.anchors <- FindIntegrationAnchors(
  object.list = object.list,
  anchor.features = rownames(sample1),
  reduction = "rlsi",
  dims = 2:30
)


library(future)

plan("sequential")

options(future.globals.maxSize = 16000 * 1024^2)

integrated<-IntegrateData(
  integration.anchors, 
  new.assay.name = "integrated",
  normalization.method = c("LogNormalize", "SCT"),
  dims = 1:27, 
  sd.weight = 1,
  eps = 0, 
  verbose = TRUE 
)

```
**Error is the following: 
Error in Embeddings(reduction)[nn.cells2, dims]: subscript out of bounds.** 

Any suggestions?

**Comment by timoast** [comment]
Hi, please open an issue on the [Seurat github page](https://github.com/satijalab/seurat) and include your full code and output of `sessionInfo()`, since these functions are part of Seurat.

I would also highly recommend using the IntegrateEmbeddings function for scATAC-seq rather than IntegrateData. See vignette [here](https://stuartlab.org/signac/articles/integrate_atac.html)
