### ISSUE TITLE
How to read in barcode, matrix and peaks file ? - ReadMtx() does not work!

### ISSUE THREAD

**Issue by Nidane** [stuart-lab/signac#1380]
Sorry for posting again. 
So basically following this https://github.com/stuart-lab/signac/issues/1377 

And as suggested I try ReadMtx() function: https://satijalab.org/seurat/reference/readmtx 

And it still does not work? 

expression_matrix <- ReadMtx(
mtx = "C:/Users/GSE158178_RAW/NC/matrix.mtx", features = "C:/Users/GSE158178_RAW/NC/peaks.bed",
cells = "C:/Users/GSE158178_RAW/NC/barcodes.tsv"
)
Error in make.unique(names = feature.names) :
'names' must be a character vector

I assume it's bc of the peak file the locations of the peaks (instead of gene names it's numbers) ?

ps: i have tried reading both .tsv or .tsv.gz and same error

thanks!

**Comment by timoast** [comment]
Yes the issue is that the peaks are 3 columns rather than a single column as is being assumed by the function. My suggestion is rather than using the `ReadMtx()` function, you can load the information into R yourself using `Matrix::readMM()` and set the row and column names correctly based on the `peaks.bed` and `barcodes.tsv` file.

If you have further questions about `Read10x()` please open an issue in the Seurat repo, as that's a Seurat function and not part of Signac.
