### ISSUE TITLE
can i do the analysis without fragment file ?

### ISSUE THREAD

**Issue by EclaiRosicky** [stuart-lab/signac#1396]
sorry i am pretty new to this. 

so i am trying to reanalyze some published data and all they could provide is the matrix, barcode, and peak file. 

since most scripts or codes i found would need the fragment file, so i wonder in this case whether i could still do the analysis ? 

thank you!

**Comment by timoast** [comment]
It depends what analysis steps you're trying to run, you can use some but not all functions without a fragment file. The error message should generally tell you if you're trying to run something that needs a fragment file. Fragment files are needed when you need access to data from the whole genome, rather than only the count matrix (for example, create coverage plot, quantify peaks, TF footprinting, TSS enrichment...)
