### ISSUE TITLE
Add peaks to seurat object in multiome analysis (Error: Cannot add more or fewer cell meta.data information without values being named with cell names)

### ISSUE THREAD

**Issue by Lei-Guo** [stuart-lab/signac#1423]
Dear developers,

I'm working on a multiome dataset. The dataset has multiple samples. I first worked on the scRNAseq dataset and finished integration, clustering and cell type annotation. I then switched to scATACseq dataset and finished QC, peak calling and merging. Now I want to add the merged scATACseq to the scRNAseq Seurat object using "sc_obj_rna[["peaks"]] <- peaks_chrom_assay_merge" but am encountering this error message "Cannot add more or fewer cell meta.data information without values being named with cell names". Below is my code. Can you please help me? Thanks.

```
peaks_chrom_assay_merge <- merge(peaks_chrom_assay[[1]], peaks_chrom_assay[-1])

cell_id_com <- intersect(colnames(sc_obj_rna), colnames(peaks_chrom_assay_merge))

sc_obj_rna <- sc_obj_rna[, cell_id_com]
peaks_chrom_assay_merge <- peaks_chrom_assay_merge[, cell_id_com]

sc_obj_rna[["peaks"]] <- peaks_chrom_assay_merge # peaks_chrom_assay_merge is merged chromatin assay
```

**Comment by timoast** [comment]
Not sure what the issue here is but I'd suggest following the vignette (https://stuartlab.org/signac/articles/pbmc_multiomic.html) and creating separate assays within one object rather than separate objects for ATAC and RNA and then merging them. If you still have issue please open an issue in the Seurat repo as this is related to Seurat not Signac
