### ISSUE TITLE
Footprinting output

### ISSUE THREAD

**Issue by valentinaOpazo** [stuart-lab/signac#1439]
Hi Signac's team.
I'm recently run a footprinting analysis in my dataset. I used _footprint()_ function on the default configuration and then I extract data using _GetFootprintingData()_ function. The output of this function is a data frame with 6 columns, where can I find documentation about the meaning of each col?? I assume that 'norm.value' may represent the normalized intensity or strength of the footprint signal, it's correct??.
Additionally, I would like to know if it's possible to obtain for each TF a measure of the relative protection of the motif binding site and a measure of DNA accessibility in regions adjacent to the motif binding site, similar to calculation by Corces and colleagues in 2018 and called footprint depth and flanking accesibility respectivitly (https://www.science.org/doi/10.1126/science.aav1898).

Thank you

**Comment by valentinaOpazo** [comment]
Also, I would like to know if it is possible to have the output of the _GetFootprintData()_ function show values for each cell instead of a single value

**Comment by timoast** [comment]
Hi, I've now updated the documentation for this function

> Additionally, I would like to know if it's possible to obtain for each TF a measure of the relative protection of the motif binding site and a measure of DNA accessibility in regions adjacent to the motif binding site, similar to calculation by Corces and colleagues in 2018 and called footprint depth and flanking accesibility respectivitly (https://www.science.org/doi/10.1126/science.aav1898).

You can look at the footprinting value in the region flanking the motif itself. We don't have a function to return this value so you would need to compute that yourself. There is some similar code in the `PlotFootprint` function that you could look at.

> 
Also, I would like to know if it is possible to have the output of the GetFootprintData() function show values for each cell instead of a single value

The `GetFootprintData()` function performs averaging across groups of cells. If you want per-cell data you can extract a matrix of cell x position with Tn5 counts by extracting the data stored in the position enrichment slot:

```r
positionEnrichment <- GetAssayData(
    object = object,
    assay = assay,
    slot = "positionEnrichment"
  )
```
