### ISSUE TITLE
CSI index support

### ISSUE THREAD

**Issue by BioFalcon** [stuart-lab/signac#1494]
Hi,

I am currently working with scATAC-seq data and I'm getting the following error:

`Requested file does not exist or is not indexed`

My fragment file is index but it is a CSI index due to the chromosome sizes being > 500Mb. I was just wondering if you guys are planning on implementing support for CSI indexes, because splitting the genome into pieces is quite annoying. 

Thanks,
F

**Comment by timoast** [comment]
Hi @BioFalcon 

I tried using a csi index and tbi index and got identical results, so it looks like this is already supported by the Rsamtools package that we use for accessing the tabix file. You can rename your .csi index file to have a .tbi extension and everything should work as normal. I will work on updating the package to allow the .csi file extension to make the workflow a bit easier.

**Comment by timoast** [comment]
This has now been updated on the develop branch

**Comment by diego-rt** [comment]
Hi,

We just tracked the error to this line of Rsamtools: 

https://github.com/Bioconductor/Rsamtools/blob/devel/src/utilities.c#L293

Editing this line seems to have fixed the problem since that limit seems to be outdated and as far as I understand dates back to when Rsamtools brought its own (old) copy of samtools. Increasing the limit did not seem to have caused any issues so far:

https://github.com/diego-rt/Rsamtools-csi/blob/devel/src/utilities.c#L293

We will keep testing and report if we encounter any issues. In the meantime, we encountered other Signac functions that seem to still search for TBI indexes:

```
> CoveragePlot(Head, assay = "ATAC", region = GRanges(seqnames = "chr4q", ranges = IRanges(start = 787659854, end = 787673983)))             
Error: TabixFile: file(s) do not exist:
  ‘~/Results/NewFragments/fragments.tsv.gz.tbi’
```

Many thanks!

**Comment by timoast** [comment]
Ok, those issues with CoveragePlot should be fixed now.

Unfortunately the larger issue with Rsamtools will need to be fixed on their side, I see you opened an issue there so hopefully they can provide a fix.

**Comment by diego-rt** [comment]
Super thanks a lot!

We encountered another error though:

```
SCData <- merge(Head, y = Larvae, add.cell.ids = c("Head", "Larvae"))
Warning message:
In merge.ChromatinAssay(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],  :
  Some fragment files are not valid or not indexed.
            Removing invalid files from merged ChromatinAssay
```

**Comment by timoast** [comment]
Hi @diego-rt, sorry I missed this earlier. Those issues with merging with CSI index files should now be fixed on the develop branch.
