### ISSUE TITLE
qlcMatrix removed from CRAN

### ISSUE THREAD

**Issue by j-andrews7** [stuart-lab/signac#1570]
The [qlcMatrix](https://cran.r-project.org/package=qlcMatrix) package (necessary for `LinkPeaks`) was removed from CRAN on November 29th.

It'd be nice if whatever functionality was being used from it was implemented internally, as it seems to have a host of errors that have gone unresolved for a long time.

**Comment by timoast** [comment]
Hi @j-andrews7 thanks for pointing this out, I was not aware of this. Since we just use the `corSparse` function from qlcMatrix, I think re-implementing that function in Signac is the best way to go. It does seem like there is an easy fix for qlcMatrix to get back on CRAN (documented here https://github.com/cysouw/qlcMatrix/issues/2), but from the looks of things the package might have been abandoned.

**Comment by timoast** [comment]
In the meantime for anyone having issues installing qlcMatrix:

```r
remotes::install_github("cysouw/qlcMatrix")
```

**Comment by timoast** [comment]
This has now been updated on the develop branch
