### ISSUE TITLE
LinkPeaks, FindMarkers functions not working on RStudio AWS Server

### ISSUE THREAD

**Issue by chsnys** [stuart-lab/signac#1706]
```r
# insert reproducible example here
```
Hi, while i write the same code with same versions of packages in Desktop RStudio app, the **LinkPeaks, FindMarkers** functions are running smoothly and i am seeing output within 5 mins, but when i am running the same code using these functions in AWS RStudio server, the code is not running and i am seeing R session aborted within two hours. the server has double the capacity of RAM, the Desktop Application has, i am not seeing how much the function is processing even when i set Verbose to TRUE. can you please provide support to this issue?

**Comment by timoast** [comment]
Hi @chsnys, not sure what to suggest here, this sounds like it could be some issue with RStudio/AWS rather than Signac. Maybe you can try running as an Rscript on aws to narrow down whether the issue is specific to aws or RStudio? If you're able to provide a small reproducible example I can try on an AWS instance and see if I can reproduce the issue

**Comment by timoast** [comment]
Closing this now as I haven't heard back, please reopen if you are able to provide the reproducible example
