### ISSUE TITLE
CreateMotifObject error

### ISSUE THREAD

**Issue by sugiYag** [stuart-lab/signac#1769]
when I use addmotifs function, the error occurs as follows:

 AddMotifs(
  object = pbmc,
  genome = BSgenome.Hsapiens.UCSC.hg19,
  pfm = pfm
)

Building motif matrix
Finding motif positions
Creating Motif object
Warning in CreateMotifObject(data = motif.matrix, positions = motif.positions,  :
  Non-unique motif names supplied, making unique

so I check whether there are some duplicated motif or not using make.unique function but there's no duplicated motif.
for this reason, i just wanna know why this warning occur

**Comment by timoast** [comment]
Hi, there doesn't seem to be any error here. What you're seeing is a warning stating that some of the motif names supplied were not unique, and they are being modified so that they are unique. If that's not what you want you could investigate why there are non-unique motif names in the matrix that you're supplying
